# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RiskPattern(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ref': 'str',
        'name': 'str',
        'desc': 'str',
        'tags': 'list[str]',
        'weaknesses': 'list[LibraryWeakness]',
        'countermeasures': 'list[LibraryControl]',
        'usecases': 'list[LibraryUseCase]'
    }

    attribute_map = {
        'ref': 'ref',
        'name': 'name',
        'desc': 'desc',
        'tags': 'tags',
        'weaknesses': 'weaknesses',
        'countermeasures': 'countermeasures',
        'usecases': 'usecases'
    }

    def __init__(self, ref=None, name=None, desc=None, tags=None, weaknesses=None, countermeasures=None, usecases=None):  # noqa: E501
        """RiskPattern - a model defined in Swagger"""  # noqa: E501

        self._ref = None
        self._name = None
        self._desc = None
        self._tags = None
        self._weaknesses = None
        self._countermeasures = None
        self._usecases = None
        self.discriminator = None

        if ref is not None:
            self.ref = ref
        if name is not None:
            self.name = name
        if desc is not None:
            self.desc = desc
        if tags is not None:
            self.tags = tags
        if weaknesses is not None:
            self.weaknesses = weaknesses
        if countermeasures is not None:
            self.countermeasures = countermeasures
        if usecases is not None:
            self.usecases = usecases

    @property
    def ref(self):
        """Gets the ref of this RiskPattern.  # noqa: E501


        :return: The ref of this RiskPattern.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this RiskPattern.


        :param ref: The ref of this RiskPattern.  # noqa: E501
        :type: str
        """

        self._ref = ref

    @property
    def name(self):
        """Gets the name of this RiskPattern.  # noqa: E501


        :return: The name of this RiskPattern.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RiskPattern.


        :param name: The name of this RiskPattern.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def desc(self):
        """Gets the desc of this RiskPattern.  # noqa: E501


        :return: The desc of this RiskPattern.  # noqa: E501
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc):
        """Sets the desc of this RiskPattern.


        :param desc: The desc of this RiskPattern.  # noqa: E501
        :type: str
        """

        self._desc = desc

    @property
    def tags(self):
        """Gets the tags of this RiskPattern.  # noqa: E501

        List of tags  # noqa: E501

        :return: The tags of this RiskPattern.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this RiskPattern.

        List of tags  # noqa: E501

        :param tags: The tags of this RiskPattern.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def weaknesses(self):
        """Gets the weaknesses of this RiskPattern.  # noqa: E501


        :return: The weaknesses of this RiskPattern.  # noqa: E501
        :rtype: list[LibraryWeakness]
        """
        return self._weaknesses

    @weaknesses.setter
    def weaknesses(self, weaknesses):
        """Sets the weaknesses of this RiskPattern.


        :param weaknesses: The weaknesses of this RiskPattern.  # noqa: E501
        :type: list[LibraryWeakness]
        """

        self._weaknesses = weaknesses

    @property
    def countermeasures(self):
        """Gets the countermeasures of this RiskPattern.  # noqa: E501


        :return: The countermeasures of this RiskPattern.  # noqa: E501
        :rtype: list[LibraryControl]
        """
        return self._countermeasures

    @countermeasures.setter
    def countermeasures(self, countermeasures):
        """Sets the countermeasures of this RiskPattern.


        :param countermeasures: The countermeasures of this RiskPattern.  # noqa: E501
        :type: list[LibraryControl]
        """

        self._countermeasures = countermeasures

    @property
    def usecases(self):
        """Gets the usecases of this RiskPattern.  # noqa: E501


        :return: The usecases of this RiskPattern.  # noqa: E501
        :rtype: list[LibraryUseCase]
        """
        return self._usecases

    @usecases.setter
    def usecases(self, usecases):
        """Sets the usecases of this RiskPattern.


        :param usecases: The usecases of this RiskPattern.  # noqa: E501
        :type: list[LibraryUseCase]
        """

        self._usecases = usecases

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RiskPattern, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RiskPattern):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
