# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TestCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'steps': 'str',
        'notes': 'str'
    }

    attribute_map = {
        'steps': 'steps',
        'notes': 'notes'
    }

    def __init__(self, steps=None, notes=None):  # noqa: E501
        """TestCommand - a model defined in Swagger"""  # noqa: E501

        self._steps = None
        self._notes = None
        self.discriminator = None

        if steps is not None:
            self.steps = steps
        if notes is not None:
            self.notes = notes

    @property
    def steps(self):
        """Gets the steps of this TestCommand.  # noqa: E501

        Test steps  # noqa: E501

        :return: The steps of this TestCommand.  # noqa: E501
        :rtype: str
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this TestCommand.

        Test steps  # noqa: E501

        :param steps: The steps of this TestCommand.  # noqa: E501
        :type: str
        """

        self._steps = steps

    @property
    def notes(self):
        """Gets the notes of this TestCommand.  # noqa: E501

        Test notes  # noqa: E501

        :return: The notes of this TestCommand.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this TestCommand.

        Test notes  # noqa: E501

        :param notes: The notes of this TestCommand.  # noqa: E501
        :type: str
        """

        self._notes = notes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
