# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ArchitectureDiagram(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'draft': 'bool',
        'schema': 'str'
    }

    attribute_map = {
        'draft': 'draft',
        'schema': 'schema'
    }

    def __init__(self, draft=None, schema=None):  # noqa: E501
        """ArchitectureDiagram - a model defined in Swagger"""  # noqa: E501

        self._draft = None
        self._schema = None
        self.discriminator = None

        if draft is not None:
            self.draft = draft
        if schema is not None:
            self.schema = schema

    @property
    def draft(self):
        """Gets the draft of this ArchitectureDiagram.  # noqa: E501


        :return: The draft of this ArchitectureDiagram.  # noqa: E501
        :rtype: bool
        """
        return self._draft

    @draft.setter
    def draft(self, draft):
        """Sets the draft of this ArchitectureDiagram.


        :param draft: The draft of this ArchitectureDiagram.  # noqa: E501
        :type: bool
        """

        self._draft = draft

    @property
    def schema(self):
        """Gets the schema of this ArchitectureDiagram.  # noqa: E501

        The representation of the architecture diagram in Draw.io XML format encoded in Base64  # noqa: E501

        :return: The schema of this ArchitectureDiagram.  # noqa: E501
        :rtype: str
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this ArchitectureDiagram.

        The representation of the architecture diagram in Draw.io XML format encoded in Base64  # noqa: E501

        :param schema: The schema of this ArchitectureDiagram.  # noqa: E501
        :type: str
        """

        self._schema = schema

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ArchitectureDiagram, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArchitectureDiagram):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
