# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unassign_groups_product_request_body import UnassignGroupsProductRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUnassignGroupsProductRequestBody(unittest.TestCase):
    """UnassignGroupsProductRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnassignGroupsProductRequestBody(self):
        """Test UnassignGroupsProductRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unassign_groups_product_request_body.UnassignGroupsProductRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
