# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_use_case_library_request_body import CreateUseCaseLibraryRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateUseCaseLibraryRequestBody(unittest.TestCase):
    """CreateUseCaseLibraryRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUseCaseLibraryRequestBody(self):
        """Test CreateUseCaseLibraryRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_use_case_library_request_body.CreateUseCaseLibraryRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
