# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.libraries_api import LibrariesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLibrariesApi(unittest.TestCase):
    """LibrariesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.libraries_api.LibrariesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_libraries_library_ref_delete(self):
        """Test case for libraries_library_ref_delete

        Deletes a Library  # noqa: E501
        """
        pass

    def test_libraries_library_ref_get(self):
        """Test case for libraries_library_ref_get

        Gets library details  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_post(self):
        """Test case for libraries_library_ref_riskpatterns_post

        Creates new Risk Pattern  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_countermeasures_post(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_countermeasures_post

        Creates new countermeasure in a risk pattern  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_delete(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_delete

        Deletes a Risk Pattern  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_get(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_get

        Gets Risk Pattern details  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_post(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_post

        Creates new use case in a library.  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_post(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_post

        Creates a new threat in a library.  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_threat_ref_countermeasures_put(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_threat_ref_countermeasures_put

        Associates a countermeasure to a threat in a risk pattern.  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_threat_ref_weaknesses_put(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_threat_ref_weaknesses_put

        Associates weakness to a threat in a risk pattern.  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_threat_ref_weaknesses_weakness_ref_countermeasures_put(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_usecases_use_case_ref_threats_threat_ref_weaknesses_weakness_ref_countermeasures_put

        Associates a countermeasure to a weakness in a risk pattern.  # noqa: E501
        """
        pass

    def test_libraries_library_ref_riskpatterns_risk_pattern_ref_weaknesses_post(self):
        """Test case for libraries_library_ref_riskpatterns_risk_pattern_ref_weaknesses_post

        Creates a new weakness in a risk pattern  # noqa: E501
        """
        pass

    def test_libraries_post(self):
        """Test case for libraries_post

        Creates a Library  # noqa: E501
        """
        pass

    def test_products_upload_post(self):
        """Test case for products_upload_post

        Creates a new product, library or template from a XML file upload.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
