# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.threat_short import ThreatShort  # noqa: E501
from swagger_client.rest import ApiException


class TestThreatShort(unittest.TestCase):
    """ThreatShort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThreatShort(self):
        """Test ThreatShort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.threat_short.ThreatShort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
