# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unassing_users_group_request_body import UnassingUsersGroupRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUnassingUsersGroupRequestBody(unittest.TestCase):
    """UnassingUsersGroupRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnassingUsersGroupRequestBody(self):
        """Test UnassingUsersGroupRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unassing_users_group_request_body.UnassingUsersGroupRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
