# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iriusrisk_python_client_lib
from iriusrisk_python_client_lib.models.associate_countermeasure_threat_library_request_body import AssociateCountermeasureThreatLibraryRequestBody  # noqa: E501
from iriusrisk_python_client_lib.rest import ApiException


class TestAssociateCountermeasureThreatLibraryRequestBody(unittest.TestCase):
    """AssociateCountermeasureThreatLibraryRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociateCountermeasureThreatLibraryRequestBody(self):
        """Test AssociateCountermeasureThreatLibraryRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iriusrisk_python_client_lib.models.associate_countermeasure_threat_library_request_body.AssociateCountermeasureThreatLibraryRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
