# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.library_use_case import LibraryUseCase  # noqa: E501
from swagger_client.rest import ApiException


class TestLibraryUseCase(unittest.TestCase):
    """LibraryUseCase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibraryUseCase(self):
        """Test LibraryUseCase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.library_use_case.LibraryUseCase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
