# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_group_request_body import UpdateGroupRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateGroupRequestBody(unittest.TestCase):
    """UpdateGroupRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateGroupRequestBody(self):
        """Test UpdateGroupRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_group_request_body.UpdateGroupRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
