# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iriusrisk_python_client_lib
from iriusrisk_python_client_lib.api.rules_api import RulesApi  # noqa: E501
from iriusrisk_python_client_lib.rest import ApiException


class TestRulesApi(unittest.TestCase):
    """RulesApi unit test stubs"""

    def setUp(self):
        self.api = iriusrisk_python_client_lib.api.rules_api.RulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rules_product_ref_put(self):
        """Test case for rules_product_ref_put

        Executes rules by a product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
