# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iriusrisk_python_client_lib
from iriusrisk_python_client_lib.models.productsrefcomponentscomponent_reftestscwe_control import ProductsrefcomponentscomponentReftestscweControl  # noqa: E501
from iriusrisk_python_client_lib.rest import ApiException


class TestProductsrefcomponentscomponentReftestscweControl(unittest.TestCase):
    """ProductsrefcomponentscomponentReftestscweControl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductsrefcomponentscomponentReftestscweControl(self):
        """Test ProductsrefcomponentscomponentReftestscweControl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iriusrisk_python_client_lib.models.productsrefcomponentscomponent_reftestscwe_control.ProductsrefcomponentscomponentReftestscweControl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
