# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_products_get(self):
        """Test case for products_get

        Gets a list of all products.  # noqa: E501
        """
        pass

    def test_products_post(self):
        """Test case for products_post

        Creates a new product  # noqa: E501
        """
        pass

    def test_products_ref_components_component_ref_controls_control_ref_status_put(self):
        """Test case for products_ref_components_component_ref_controls_control_ref_status_put

        Sets the desired status to a countermeasure  # noqa: E501
        """
        pass

    def test_products_ref_components_component_ref_tests_cwe_put(self):
        """Test case for products_ref_components_component_ref_tests_cwe_put

        Updates a single test to a component.  # noqa: E501
        """
        pass

    def test_products_ref_components_component_ref_tests_test_type_upload_post(self):
        """Test case for products_ref_components_component_ref_tests_test_type_upload_post

        Imports test results from different sources to a component  # noqa: E501
        """
        pass

    def test_products_ref_controls_get(self):
        """Test case for products_ref_controls_get

        Gets a list of all product countermeasures  # noqa: E501
        """
        pass

    def test_products_ref_controls_implemented_get(self):
        """Test case for products_ref_controls_implemented_get

        Gets a list of all implemented countermeasures of a product.  # noqa: E501
        """
        pass

    def test_products_ref_controls_required_get(self):
        """Test case for products_ref_controls_required_get

        Gets a list of all required countermeasures of a product  # noqa: E501
        """
        pass

    def test_products_ref_delete(self):
        """Test case for products_ref_delete

        Deletes a product  # noqa: E501
        """
        pass

    def test_products_ref_diagram_image_get(self):
        """Test case for products_ref_diagram_image_get

        Gets diagram image for product.  # noqa: E501
        """
        pass

    def test_products_ref_get(self):
        """Test case for products_ref_get

        Gets product details  # noqa: E501
        """
        pass

    def test_products_ref_groups_delete(self):
        """Test case for products_ref_groups_delete

        Unassigns a list of user groups from a product.  # noqa: E501
        """
        pass

    def test_products_ref_groups_get(self):
        """Test case for products_ref_groups_get

        List all groups assigned to a product  # noqa: E501
        """
        pass

    def test_products_ref_groups_put(self):
        """Test case for products_ref_groups_put

        Assigns groups of users to a product.  # noqa: E501
        """
        pass

    def test_products_ref_put(self):
        """Test case for products_ref_put

        Updates a product  # noqa: E501
        """
        pass

    def test_products_ref_risks_get(self):
        """Test case for products_ref_risks_get

        Gets the risks summary of a product  # noqa: E501
        """
        pass

    def test_products_ref_tests_test_type_upload_post(self):
        """Test case for products_ref_tests_test_type_upload_post

        Imports test results from different sources to a product.  # noqa: E501
        """
        pass

    def test_products_ref_threats_get(self):
        """Test case for products_ref_threats_get

        Gets a list of all threats of a product  # noqa: E501
        """
        pass

    def test_products_ref_users_delete(self):
        """Test case for products_ref_users_delete

        Unassigns a list of users from a product.  # noqa: E501
        """
        pass

    def test_products_ref_users_get(self):
        """Test case for products_ref_users_get

        List all users assigned to a product  # noqa: E501
        """
        pass

    def test_products_ref_users_put(self):
        """Test case for products_ref_users_put

        Assigns users to a product.  # noqa: E501
        """
        pass

    def test_products_ref_users_user_delete(self):
        """Test case for products_ref_users_user_delete

        Unassigns a user from a product  # noqa: E501
        """
        pass

    def test_products_ref_weaknesses_get(self):
        """Test case for products_ref_weaknesses_get

        Gets a list of all weaknesses of a product  # noqa: E501
        """
        pass

    def test_products_ref_weaknesses_test_state_get(self):
        """Test case for products_ref_weaknesses_test_state_get

        Gets a list of all weaknesses of a product filtered by test state  # noqa: E501
        """
        pass

    def test_products_upload_post(self):
        """Test case for products_upload_post

        Creates a new product, library or template from a XML file upload.  # noqa: E501
        """
        pass

    def test_products_upload_ref_post(self):
        """Test case for products_upload_ref_post

        Updates an existing product from a XML file upload.  # noqa: E501
        """
        pass

    def test_rules_product_ref_put(self):
        """Test case for rules_product_ref_put

        Executes rules by a product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
