# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unassign_users_product_request_body import UnassignUsersProductRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUnassignUsersProductRequestBody(unittest.TestCase):
    """UnassignUsersProductRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnassignUsersProductRequestBody(self):
        """Test UnassignUsersProductRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unassign_users_product_request_body.UnassignUsersProductRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
