# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iriusrisk_python_client_lib
from iriusrisk_python_client_lib.api.token_api import TokenApi  # noqa: E501
from iriusrisk_python_client_lib.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = iriusrisk_python_client_lib.api.token_api.TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_username_token_post(self):
        """Test case for users_username_token_post

        Generates a user API token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
