# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iriusrisk_python_client_lib
from iriusrisk_python_client_lib.models.product_short_groups import ProductShortGroups  # noqa: E501
from iriusrisk_python_client_lib.rest import ApiException


class TestProductShortGroups(unittest.TestCase):
    """ProductShortGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductShortGroups(self):
        """Test ProductShortGroups"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iriusrisk_python_client_lib.models.product_short_groups.ProductShortGroups()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
