# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iriusrisk_python_client_lib
from iriusrisk_python_client_lib.models.product_access_type import ProductAccessType  # noqa: E501
from iriusrisk_python_client_lib.rest import ApiException


class TestProductAccessType(unittest.TestCase):
    """ProductAccessType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductAccessType(self):
        """Test ProductAccessType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iriusrisk_python_client_lib.models.product_access_type.ProductAccessType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
