# coding: utf-8

"""
    IriusRisk API

    Products API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.data_flow import DataFlow  # noqa: E501
from swagger_client.rest import ApiException


class TestDataFlow(unittest.TestCase):
    """DataFlow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataFlow(self):
        """Test DataFlow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data_flow.DataFlow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
